site_name: Wholecell cell simulation

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.top

plugins:
  - search
  - blog:
      blog_dir: blog
      post_date_format: yyyy-MM-dd
      archive: true
      archive_name: By Time
      archive_date_format: MMM yyyy
      categories: true
      categories_name: By Category
      authors: true
      authors_profiles: true
      authors_profiles_name: By Author
      authors_file: docs/blog/.authors.yml
      pagination_per_page: 10
  - tags:
      tag_name: By Tags
      tag_template: docs/blog/tag.md

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'Whole-cell-simulation' # default: ''
      relative_path: '' # default ''
      absolute: true # default: false
      tags: 'a script img link object embed'

nav:
  - Home: index.md
  - Electrobiology:   
      - Cable Bacteria: 
        - Model: Electrobiology/Cable Bacteria/Model/README.md
        - Omics: Electrobiology/Cable Bacteria/Omics/README.md
      - Clostridium ljungdahlii:
        - Model: Electrobiology/Clostridium ljungdahlii/Model/README.md
        - Omics: Electrobiology/Clostridium ljungdahlii/Omics/README.md
      - Clostridium luticellarii: 
        - Model: Electrobiology/Clostridium luticellarii/Model/README.md
        - Omics: Electrobiology/Clostridium luticellarii/Omics/README.md
      - Geobactor sulfurreducens:
        - Model: Electrobiology/Geobactor sulfurreducens/Model/README.md
        - Omics: Electrobiology/Geobactor sulfurreducens/Omics/README.md
      - Geothrix fermentans: 
        - Model: Electrobiology/Geothrix fermentans/Model/README.md
        - Omics: Electrobiology/Geothrix fermentans/Omics/README.md
      - Rhodopseudomonas palustris:
        - Model: Electrobiology/Rhodopseudomonas palustris/Model/README.md
        - Omics: Electrobiology/Rhodopseudomonas palustris/Omics/README.md
      - Shewanella oneidensis:
        - Model: Electrobiology/Shewanella oneidensis/Model/README.md
        - Omics: Electrobiology/Shewanella oneidensis/Omics/README.md
      - Thauera sp. MZ1T: 
        - Model: Electrobiology/Thauera sp. MZ1T/Model/README.md
        - Omics: Electrobiology/Thauera sp. MZ1T/Omics/README.md
  - Our Works:
      - blog/index.md
      - By Tags: blog/tags.md

