site_name: Prof. Su Wholecell's Group

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.top

plugins:
  - blog:
      post_date_format: long
      post_readtime_words_per_minute: 300
      authors_profiles: true
      archive: false
  - search
  - macros
  - meta
  - social
  

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'YOUR_REPO_NAME' # default: ''
      relative_path: '' # default ''
      absolute: true # default: false
      tags: 'a script img link object embed'

nav:
  - Home: index.md
  - Electrobiology:   
      - Cable Bacteria: 
        - Model: Electrobiology/Cable Bacteria/Model/README.md
        - Omics: Electrobiology/Cable Bacteria/Omics/README.md
      - Clostridium ljungdahlii:
        - Model: Electrobiology/Clostridium ljungdahlii/Model/README.md
        - Omics: Electrobiology/Clostridium ljungdahlii/Omics/README.md
      - Clostridium luticellarii: 
        - Model: Electrobiology/Clostridium luticellarii/Model/README.md
        - Omics: Electrobiology/Clostridium luticellarii/Omics/README.md
      - Geobactor sulfurreducens:
        - Model: Electrobiology/Geobactor sulfurreducens/Model/README.md
        - Omics: Electrobiology/Geobactor sulfurreducens/Omics/README.md
      - Geothrix fermentans: 
        - Model: Electrobiology/Geothrix fermentans/Model/README.md
        - Omics: Electrobiology/Geothrix fermentans/Omics/README.md
      - Rhodopseudomonas palustris:
        - Model: Electrobiology/Rhodopseudomonas palustris/Model/README.md
        - Omics: Electrobiology/Rhodopseudomonas palustris/Omics/README.md
      - Shewanella oneidensis:
        - Model: Electrobiology/Shewanella oneidensis/Model/README.md
        - Omics: Electrobiology/Shewanella oneidensis/Omics/README.md
      - Thauera sp. MZ1T: 
        - Model: Electrobiology/Thauera sp. MZ1T/Model/README.md
        - Omics: Electrobiology/Thauera sp. MZ1T/Omics/README.md
  - Model Collection:
      - E. coli: Model collection/E coli/README.md
      - S. cerevisiae: Model collection/S.cerevisiae/README.md
  - Weekly Progress:
      - Bao: Weekly progress/Bao/README.md
      - Kim: Weekly progress/Kim/README.md
      - Rich: Weekly progress/Rich/README.md
      - Sam: Weekly progress/Sam/README.md
      - Tobby: Weekly progress/Tobby/README.md
      - Xiaoguang: Weekly progress/Xiaoguang/README.md
  - Blog: blog/index.md

